version: "3"

tasks:
  swag:
    cmds:
      - swag init
    silent: true
    desc: Generate swagger docs
  build:
    cmds:
      - go build -ldflags "-s -w" -o bin/app
  run:
    cmds:
      - go run main.go
    desc: Run the application
