// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Michele Dinelli",
            "email": "dinellimichele00@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/archive": {
            "get": {
                "description": "Return the list of all the archive images with their metadata. The response is paginated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "archive"
                ],
                "summary": "Returns a paginated response with the list of archive images",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page index starting from 0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of items per page",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The list of archive images",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedResponseModel-models_AculeiImage"
                        }
                    },
                    "500": {
                        "description": "An error occurred",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        },
        "/v1/archive/image/{id}": {
            "get": {
                "description": "Returns a single archive with its metadata",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "archive"
                ],
                "summary": "Returns a single archive image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the archive image id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The archive image and its metadata",
                        "schema": {
                            "$ref": "#/definitions/models.AculeiImage"
                        }
                    },
                    "500": {
                        "description": "An error occurred",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        },
        "/v1/experience/random": {
            "get": {
                "description": "Returns a random image. Randomness is achieved using sample aggregation in MongoDB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experience"
                ],
                "summary": "Returns a random image to be displayed in the experience page",
                "responses": {
                    "200": {
                        "description": "The random image",
                        "schema": {
                            "$ref": "#/definitions/models.AculeiImage"
                        }
                    },
                    "500": {
                        "description": "An error occurred",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        },
        "/v1/filters": {
            "get": {
                "description": "Returns the list of available filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filters"
                ],
                "summary": "Returns the list of available filters",
                "responses": {
                    "200": {
                        "description": "The list of available filters",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Filter"
                            }
                        }
                    },
                    "500": {
                        "description": "An error occurred",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AculeiImage": {
            "type": "object",
            "properties": {
                "cam": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_name": {
                    "type": "string"
                },
                "moon_phase": {
                    "type": "string"
                },
                "predicted_animal": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "models.ErrorResponseModel": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "invalid"
                }
            }
        },
        "models.Filter": {
            "type": "object",
            "properties": {
                "from": {},
                "name": {
                    "type": "string"
                },
                "to": {},
                "values": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "models.PaginatedResponseModel-models_AculeiImage": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AculeiImage"
                    }
                },
                "next": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "aculei-be",
	Description:      "Live to serve aculei.xyz",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
