basePath: /
definitions:
  models.AculeiImage:
    properties:
      cam:
        example: CAM7
        type: string
      date:
        example: "2021-01-25T03:01:32+01:00"
        type: string
      id:
        example: 76288dfbf134376e0b6fae8d8ff87c26
        type: string
      image_name:
        example: TF_ACULEI_25012021-203.jpg
        type: string
      moon_phase:
        example: Waning Gibbous
        type: string
      predicted_animal:
        example: fox
        type: string
      temperature:
        example: 12.5
        type: number
      top_predictions:
        example: '[{''score'': 0.9460213780403137, ''label'': ''porcupine''}, {''score'':
          0.03565983474254608, ''label'': ''wild boar''}, {''score'': 0.012196173891425133,
          ''label'': ''badger''}]'
        type: string
    type: object
  models.ErrorResponseModel:
    properties:
      detail:
        example: detail
        type: string
      message:
        example: invalid
        type: string
    type: object
  models.Filter:
    properties:
      from: {}
      name:
        type: string
      to: {}
      values:
        items: {}
        type: array
    type: object
  models.PaginatedResponseModel-models_AculeiImage:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/models.AculeiImage'
        type: array
      next:
        type: integer
      page:
        type: integer
      size:
        type: integer
      sortby:
        type: string
      total:
        type: integer
    type: object
host: localhost:8888
info:
  contact:
    email: dinellimichele00@gmail.com
    name: Michele Dinelli
  description: Live to serve aculei.xyz
  title: aculei-be
  version: 0.0.1
paths:
  /v1/archive:
    get:
      consumes:
      - application/json
      description: Return the list of all the archive images with their metadata.
        The response is paginated.
      parameters:
      - description: page index starting from 0
        in: query
        name: page
        type: integer
      - description: number of items per page
        in: query
        name: size
        type: integer
      - default: date
        description: key to sort by
        enum:
        - date
        - cam
        - animal
        - temperature
        - moon_phase
        in: query
        name: sortBy
        type: string
      - collectionFormat: multi
        description: list of animals
        in: query
        items:
          type: string
        name: animal
        type: array
      - collectionFormat: multi
        description: list of moon phases
        in: query
        items:
          type: string
        name: moon_phase
        type: array
      - collectionFormat: multi
        description: list of temperatures
        in: query
        items:
          type: integer
        name: temperature
        type: array
      - collectionFormat: multi
        description: list of dates
        in: query
        items:
          type: string
        name: date
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: The list of archive images with pagination metadata
          schema:
            $ref: '#/definitions/models.PaginatedResponseModel-models_AculeiImage'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
      summary: Returns a paginated response with the list of archive images
      tags:
      - archive
  /v1/archive/image/{id}:
    get:
      consumes:
      - application/json
      description: Returns a single archive with its metadata
      parameters:
      - description: the archive image id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The archive image and its metadata
          schema:
            $ref: '#/definitions/models.AculeiImage'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
      summary: Returns a single archive image
      tags:
      - archive
  /v1/experience/image/{id}:
    get:
      consumes:
      - application/json
      description: Returns a single experience with its metadata
      parameters:
      - description: the experience image id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The experience image and its metadata
          schema:
            $ref: '#/definitions/models.AculeiImage'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
      summary: Returns a single experience image
      tags:
      - experience
  /v1/experience/random:
    get:
      consumes:
      - application/json
      description: Returns a random image. Randomness is achieved using sample aggregation
        in MongoDB.
      produces:
      - application/json
      responses:
        "200":
          description: The random image
          schema:
            $ref: '#/definitions/models.AculeiImage'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
      summary: Returns a random image to be displayed in the experience page
      tags:
      - experience
  /v1/filters:
    get:
      consumes:
      - application/json
      description: Returns the list of available filters
      produces:
      - application/json
      responses:
        "200":
          description: The list of available filters
          schema:
            items:
              $ref: '#/definitions/models.Filter'
            type: array
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
      summary: Returns the list of available filters
      tags:
      - filters
schemes:
- http
- https
swagger: "2.0"
