basePath: /
definitions:
  models.AculeiImage:
    properties:
      cam:
        example: CAM5
        type: string
      date:
        example: "2021-06-01 22:47:09"
        type: string
      id:
        example: d38a0ec061a460466c253efe9a62cb14
        type: string
      image_name:
        example: TF_ACULEI_01062021-2741.jpg
        type: string
      moon_phase:
        example: Waning Crescent
        type: string
      predicted_animal:
        example: fox
        type: string
      temperature:
        example: 12
        type: number
    type: object
  models.ErrorResponseModel:
    properties:
      message:
        example: invalid
        type: string
      param:
        example: param_name
        type: string
      params:
        example:
        - param1
        - param2
        items:
          type: string
        type: array
    type: object
  models.PaginatedResponseModel-models_AculeiImage:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/models.AculeiImage'
        type: array
      next:
        type: integer
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
host: localhost:8888
info:
  contact:
    email: dinellimichele00@gmail.com
    name: Michele Dinelli
  description: Live to serve aculei.xyz
  title: aculei-be
  version: 0.0.1
paths:
  /v1/archive:
    get:
      consumes:
      - application/json
      description: Return the list of all the archive images with their metadata.
        The response is paginated.
      parameters:
      - description: page index starting from 0
        in: query
        name: page
        type: integer
      - description: number of items per page
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: The list of archive images
          schema:
            $ref: '#/definitions/models.PaginatedResponseModel-models_AculeiImage'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
      summary: Returns a paginated response with the list of archive images
      tags:
      - archive
  /v1/archive/image/{id}:
    get:
      consumes:
      - application/json
      description: Returns a single archive with its metadata
      parameters:
      - description: the archive image id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The archive image and its metadata
          schema:
            $ref: '#/definitions/models.AculeiImage'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
      summary: Returns a single archive image
      tags:
      - archive
schemes:
- http
- https
swagger: "2.0"
