definitions:
  models.Dataset:
    properties:
      badger:
        type: string
      buzzard:
        type: string
      camera_1_coordinates:
        type: string
      camera_2_coordinates:
        type: string
      camera_3_coordinates:
        type: string
      camera_4_coordinates:
        type: string
      camera_5_coordinates:
        type: string
      camera_6_coordinates:
        type: string
      camera_7_coordinates:
        type: string
      cat:
        type: string
      deer:
        type: string
      fox:
        type: string
      hare:
        type: string
      heron:
        type: string
      horse:
        type: string
      mallard:
        type: string
      marten:
        type: string
      photos_autumn:
        type: string
      photos_camera_1:
        type: string
      photos_camera_2:
        type: string
      photos_camera_3:
        type: string
      photos_camera_4:
        type: string
      photos_camera_5:
        type: string
      photos_camera_6:
        type: string
      photos_camera_7:
        type: string
      photos_spring:
        type: string
      photos_summer:
        type: string
      photos_winter:
        type: string
      porcupine:
        type: string
      squirrel:
        type: string
      total_records:
        type: string
      wild_boar:
        type: string
      wolf:
        type: string
    type: object
  models.ErrorInternalServerError:
    properties:
      message:
        example: internal server error
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: dinellimichele00@gmail.com
    name: Michele Dinelli
  description: The purpose of this microservice is to serve aculei.xyz
  title: aculei-be
  version: 0.0.1
paths:
  /v1/dataset:
    get:
      consumes:
      - application/json
      description: Return info about dataset like number of records, number of columns,
        etc.
      produces:
      - application/json
      responses:
        "200":
          description: The dataset info
          schema:
            $ref: '#/definitions/models.Dataset'
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorInternalServerError'
      summary: return dataset info
      tags:
      - dataset
swagger: "2.0"
