definitions:
  models.Archive:
    properties:
      cam:
        example: CAM5
        type: string
      date:
        example: "2021-06-01 22:47:09"
        type: string
      id:
        example: d38a0ec061a460466c253efe9a62cb14
        type: string
      image_name:
        example: TF_ACULEI_01062021-2741.jpg
        type: string
      moon_phase:
        example: Waning Crescent
        type: string
      predicted_animal:
        example: fox
        type: string
      temperature:
        example: 12
        type: number
    type: object
  models.ErrorResponseModel:
    properties:
      message:
        example: invalid
        type: string
      param:
        example: param_name
        type: string
      params:
        example:
        - param1
        - param2
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: dinellimichele00@gmail.com
    name: Michele Dinelli
  description: Live to serve aculei.xyz
  title: aculei-be
  version: 0.0.1
paths:
  /v1/archive:
    get:
      consumes:
      - application/json
      description: Return the list of all the archive images with their metadata
      produces:
      - application/json
      responses:
        "200":
          description: The list of archive images
          schema:
            items:
              $ref: '#/definitions/models.Archive'
            type: array
        "500":
          description: An error occurred
          schema:
            $ref: '#/definitions/models.ErrorResponseModel'
      summary: Return a list of archive images
      tags:
      - archive
swagger: "2.0"
